# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management_db
spring.datasource.username=Dartlay
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# Disable JPA autoconfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html