# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management_db
spring.datasource.username=Dartlay
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html